version: 2
jobs:
  build:

    working_directory: "/go/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"

    docker:
      - image: golang:1.9

    steps:
      - checkout

      - run: ls -lart && pwd
      - run: go test -v ./...
